#include <stdint.h>

#if 0
/usr/local/google/home/gfan/proj/VulkanSamples/API-Samples/android/../input_attachment/input_attachment.frag
// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 19

                              Capability Shader
                              Capability InputAttachment
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 9
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "outColor"
                              Name 12  "myInputAttachment"
                              Decorate 9(outColor) Location 0
                              Decorate 12(myInputAttachment) DescriptorSet 0
                              Decorate 12(myInputAttachment) Binding 0
                              Decorate 12(myInputAttachment) InputAttachmentIndex 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Output 7(fvec4)
     9(outColor):      8(ptr) Variable Output
              10:             TypeImage 6(float) SubpassData nonsampled format:Unknown
              11:             TypePointer UniformConstant 10
12(myInputAttachment):     11(ptr) Variable UniformConstant
              14:             TypeInt 32 1
              15:     14(int) Constant 0
              16:             TypeVector 14(int) 2
              17:   16(ivec2) ConstantComposite 15 15
         4(main):           2 Function None 3
               5:             Label
              13:          10 Load 12(myInputAttachment)
              18:    7(fvec4) ImageRead 13 17
                              Store 9(outColor) 18
                              Return
                              FunctionEnd
#endif

static const uint32_t input_attachment_frag[137] = {
    0x07230203, 0x00010000, 0x00080007, 0x00000013,
    0x00000000, 0x00020011, 0x00000001, 0x00020011,
    0x00000028, 0x0006000b, 0x00000001, 0x4c534c47,
    0x6474732e, 0x3035342e, 0x00000000, 0x0003000e,
    0x00000000, 0x00000001, 0x0006000f, 0x00000004,
    0x00000004, 0x6e69616d, 0x00000000, 0x00000009,
    0x00030010, 0x00000004, 0x00000007, 0x00030003,
    0x00000002, 0x000001c2, 0x00040005, 0x00000004,
    0x6e69616d, 0x00000000, 0x00050005, 0x00000009,
    0x4374756f, 0x726f6c6f, 0x00000000, 0x00070005,
    0x0000000c, 0x6e49796d, 0x41747570, 0x63617474,
    0x6e656d68, 0x00000074, 0x00040047, 0x00000009,
    0x0000001e, 0x00000000, 0x00040047, 0x0000000c,
    0x00000022, 0x00000000, 0x00040047, 0x0000000c,
    0x00000021, 0x00000000, 0x00040047, 0x0000000c,
    0x0000002b, 0x00000000, 0x00020013, 0x00000002,
    0x00030021, 0x00000003, 0x00000002, 0x00030016,
    0x00000006, 0x00000020, 0x00040017, 0x00000007,
    0x00000006, 0x00000004, 0x00040020, 0x00000008,
    0x00000003, 0x00000007, 0x0004003b, 0x00000008,
    0x00000009, 0x00000003, 0x00090019, 0x0000000a,
    0x00000006, 0x00000006, 0x00000000, 0x00000000,
    0x00000000, 0x00000002, 0x00000000, 0x00040020,
    0x0000000b, 0x00000000, 0x0000000a, 0x0004003b,
    0x0000000b, 0x0000000c, 0x00000000, 0x00040015,
    0x0000000e, 0x00000020, 0x00000001, 0x0004002b,
    0x0000000e, 0x0000000f, 0x00000000, 0x00040017,
    0x00000010, 0x0000000e, 0x00000002, 0x0005002c,
    0x00000010, 0x00000011, 0x0000000f, 0x0000000f,
    0x00050036, 0x00000002, 0x00000004, 0x00000000,
    0x00000003, 0x000200f8, 0x00000005, 0x0004003d,
    0x0000000a, 0x0000000d, 0x0000000c, 0x00050062,
    0x00000007, 0x00000012, 0x0000000d, 0x00000011,
    0x0003003e, 0x00000009, 0x00000012, 0x000100fd,
    0x00010038,
};
