#include <stdint.h>

#if 0
/usr/local/google/home/gfan/proj/VulkanSamples/API-Samples/android/../input_attachment/input_attachment.vert
// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 45

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 32 34
                              Source GLSL 450
                              Name 4  "main"
                              Name 12  "vertices"
                              Name 30  "gl_PerVertex"
                              MemberName 30(gl_PerVertex) 0  "gl_Position"
                              MemberName 30(gl_PerVertex) 1  "gl_PointSize"
                              MemberName 30(gl_PerVertex) 2  "gl_ClipDistance"
                              MemberName 30(gl_PerVertex) 3  "gl_CullDistance"
                              Name 32  ""
                              Name 34  "gl_VertexIndex"
                              MemberDecorate 30(gl_PerVertex) 0 BuiltIn Position
                              MemberDecorate 30(gl_PerVertex) 1 BuiltIn PointSize
                              MemberDecorate 30(gl_PerVertex) 2 BuiltIn ClipDistance
                              MemberDecorate 30(gl_PerVertex) 3 BuiltIn CullDistance
                              Decorate 30(gl_PerVertex) Block
                              Decorate 34(gl_VertexIndex) BuiltIn VertexIndex
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 2
               8:             TypeInt 32 0
               9:      8(int) Constant 3
              10:             TypeArray 7(fvec2) 9
              11:             TypePointer Private 10
    12(vertices):     11(ptr) Variable Private
              13:             TypeInt 32 1
              14:     13(int) Constant 0
              15:    6(float) Constant 3212836864
              16:    7(fvec2) ConstantComposite 15 15
              17:             TypePointer Private 7(fvec2)
              19:     13(int) Constant 1
              20:    6(float) Constant 1065353216
              21:    7(fvec2) ConstantComposite 20 15
              23:     13(int) Constant 2
              24:    6(float) Constant 0
              25:    7(fvec2) ConstantComposite 24 20
              27:             TypeVector 6(float) 4
              28:      8(int) Constant 1
              29:             TypeArray 6(float) 28
30(gl_PerVertex):             TypeStruct 27(fvec4) 6(float) 29 29
              31:             TypePointer Output 30(gl_PerVertex)
              32:     31(ptr) Variable Output
              33:             TypePointer Input 13(int)
34(gl_VertexIndex):     33(ptr) Variable Input
              36:     13(int) Constant 3
              43:             TypePointer Output 27(fvec4)
         4(main):           2 Function None 3
               5:             Label
              18:     17(ptr) AccessChain 12(vertices) 14
                              Store 18 16
              22:     17(ptr) AccessChain 12(vertices) 19
                              Store 22 21
              26:     17(ptr) AccessChain 12(vertices) 23
                              Store 26 25
              35:     13(int) Load 34(gl_VertexIndex)
              37:     13(int) SMod 35 36
              38:     17(ptr) AccessChain 12(vertices) 37
              39:    7(fvec2) Load 38
              40:    6(float) CompositeExtract 39 0
              41:    6(float) CompositeExtract 39 1
              42:   27(fvec4) CompositeConstruct 40 41 24 20
              44:     43(ptr) AccessChain 32 14
                              Store 44 42
                              Return
                              FunctionEnd
#endif

static const uint32_t input_attachment_vert[301] = {
    0x07230203, 0x00010000, 0x00080007, 0x0000002d,
    0x00000000, 0x00020011, 0x00000001, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0007000f, 0x00000000, 0x00000004, 0x6e69616d,
    0x00000000, 0x00000020, 0x00000022, 0x00030003,
    0x00000002, 0x000001c2, 0x00040005, 0x00000004,
    0x6e69616d, 0x00000000, 0x00050005, 0x0000000c,
    0x74726576, 0x73656369, 0x00000000, 0x00060005,
    0x0000001e, 0x505f6c67, 0x65567265, 0x78657472,
    0x00000000, 0x00060006, 0x0000001e, 0x00000000,
    0x505f6c67, 0x7469736f, 0x006e6f69, 0x00070006,
    0x0000001e, 0x00000001, 0x505f6c67, 0x746e696f,
    0x657a6953, 0x00000000, 0x00070006, 0x0000001e,
    0x00000002, 0x435f6c67, 0x4470696c, 0x61747369,
    0x0065636e, 0x00070006, 0x0000001e, 0x00000003,
    0x435f6c67, 0x446c6c75, 0x61747369, 0x0065636e,
    0x00030005, 0x00000020, 0x00000000, 0x00060005,
    0x00000022, 0x565f6c67, 0x65747265, 0x646e4978,
    0x00007865, 0x00050048, 0x0000001e, 0x00000000,
    0x0000000b, 0x00000000, 0x00050048, 0x0000001e,
    0x00000001, 0x0000000b, 0x00000001, 0x00050048,
    0x0000001e, 0x00000002, 0x0000000b, 0x00000003,
    0x00050048, 0x0000001e, 0x00000003, 0x0000000b,
    0x00000004, 0x00030047, 0x0000001e, 0x00000002,
    0x00040047, 0x00000022, 0x0000000b, 0x0000002a,
    0x00020013, 0x00000002, 0x00030021, 0x00000003,
    0x00000002, 0x00030016, 0x00000006, 0x00000020,
    0x00040017, 0x00000007, 0x00000006, 0x00000002,
    0x00040015, 0x00000008, 0x00000020, 0x00000000,
    0x0004002b, 0x00000008, 0x00000009, 0x00000003,
    0x0004001c, 0x0000000a, 0x00000007, 0x00000009,
    0x00040020, 0x0000000b, 0x00000006, 0x0000000a,
    0x0004003b, 0x0000000b, 0x0000000c, 0x00000006,
    0x00040015, 0x0000000d, 0x00000020, 0x00000001,
    0x0004002b, 0x0000000d, 0x0000000e, 0x00000000,
    0x0004002b, 0x00000006, 0x0000000f, 0xbf800000,
    0x0005002c, 0x00000007, 0x00000010, 0x0000000f,
    0x0000000f, 0x00040020, 0x00000011, 0x00000006,
    0x00000007, 0x0004002b, 0x0000000d, 0x00000013,
    0x00000001, 0x0004002b, 0x00000006, 0x00000014,
    0x3f800000, 0x0005002c, 0x00000007, 0x00000015,
    0x00000014, 0x0000000f, 0x0004002b, 0x0000000d,
    0x00000017, 0x00000002, 0x0004002b, 0x00000006,
    0x00000018, 0x00000000, 0x0005002c, 0x00000007,
    0x00000019, 0x00000018, 0x00000014, 0x00040017,
    0x0000001b, 0x00000006, 0x00000004, 0x0004002b,
    0x00000008, 0x0000001c, 0x00000001, 0x0004001c,
    0x0000001d, 0x00000006, 0x0000001c, 0x0006001e,
    0x0000001e, 0x0000001b, 0x00000006, 0x0000001d,
    0x0000001d, 0x00040020, 0x0000001f, 0x00000003,
    0x0000001e, 0x0004003b, 0x0000001f, 0x00000020,
    0x00000003, 0x00040020, 0x00000021, 0x00000001,
    0x0000000d, 0x0004003b, 0x00000021, 0x00000022,
    0x00000001, 0x0004002b, 0x0000000d, 0x00000024,
    0x00000003, 0x00040020, 0x0000002b, 0x00000003,
    0x0000001b, 0x00050036, 0x00000002, 0x00000004,
    0x00000000, 0x00000003, 0x000200f8, 0x00000005,
    0x00050041, 0x00000011, 0x00000012, 0x0000000c,
    0x0000000e, 0x0003003e, 0x00000012, 0x00000010,
    0x00050041, 0x00000011, 0x00000016, 0x0000000c,
    0x00000013, 0x0003003e, 0x00000016, 0x00000015,
    0x00050041, 0x00000011, 0x0000001a, 0x0000000c,
    0x00000017, 0x0003003e, 0x0000001a, 0x00000019,
    0x0004003d, 0x0000000d, 0x00000023, 0x00000022,
    0x0005008b, 0x0000000d, 0x00000025, 0x00000023,
    0x00000024, 0x00050041, 0x00000011, 0x00000026,
    0x0000000c, 0x00000025, 0x0004003d, 0x00000007,
    0x00000027, 0x00000026, 0x00050051, 0x00000006,
    0x00000028, 0x00000027, 0x00000000, 0x00050051,
    0x00000006, 0x00000029, 0x00000027, 0x00000001,
    0x00070050, 0x0000001b, 0x0000002a, 0x00000028,
    0x00000029, 0x00000018, 0x00000014, 0x00050041,
    0x0000002b, 0x0000002c, 0x00000020, 0x0000000e,
    0x0003003e, 0x0000002c, 0x0000002a, 0x000100fd,
    0x00010038,
};
