#include <stdint.h>

#if 0
/usr/local/google/home/gfan/proj/VulkanSamples/API-Samples/android/../multiple_sets/multiple_sets.frag
// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 57

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 11 16 55
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 400
                              SourceExtension  "GL_ARB_separate_shader_objects"
                              SourceExtension  "GL_ARB_shading_language_420pack"
                              Name 4  "main"
                              Name 9  "resColor"
                              Name 11  "inColor"
                              Name 16  "inTexCoords"
                              Name 55  "outColor"
                              Decorate 11(inColor) Location 0
                              Decorate 16(inTexCoords) Location 1
                              Decorate 55(outColor) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Function 7(fvec4)
              10:             TypePointer Input 7(fvec4)
     11(inColor):     10(ptr) Variable Input
              13:             TypeBool
              14:             TypeVector 6(float) 2
              15:             TypePointer Input 14(fvec2)
 16(inTexCoords):     15(ptr) Variable Input
              17:             TypeInt 32 0
              18:     17(int) Constant 0
              19:             TypePointer Input 6(float)
              22:    6(float) Constant 1008981770
              29:    6(float) Constant 1065185444
              34:    6(float) Constant 1036831949
              35:    6(float) Constant 1065353216
              36:    7(fvec4) ConstantComposite 34 34 34 35
              39:     17(int) Constant 1
              54:             TypePointer Output 7(fvec4)
    55(outColor):     54(ptr) Variable Output
         4(main):           2 Function None 3
               5:             Label
     9(resColor):      8(ptr) Variable Function
              12:    7(fvec4) Load 11(inColor)
                              Store 9(resColor) 12
              20:     19(ptr) AccessChain 16(inTexCoords) 18
              21:    6(float) Load 20
              23:    13(bool) FOrdLessThan 21 22
              24:    13(bool) LogicalNot 23
                              SelectionMerge 26 None
                              BranchConditional 24 25 26
              25:               Label
              27:     19(ptr)   AccessChain 16(inTexCoords) 18
              28:    6(float)   Load 27
              30:    13(bool)   FOrdGreaterThan 28 29
                                Branch 26
              26:             Label
              31:    13(bool) Phi 23 5 30 25
                              SelectionMerge 33 None
                              BranchConditional 31 32 33
              32:               Label
              37:    7(fvec4)   Load 9(resColor)
              38:    7(fvec4)   FMul 37 36
                                Store 9(resColor) 38
                                Branch 33
              33:             Label
              40:     19(ptr) AccessChain 16(inTexCoords) 39
              41:    6(float) Load 40
              42:    13(bool) FOrdLessThan 41 22
              43:    13(bool) LogicalNot 42
                              SelectionMerge 45 None
                              BranchConditional 43 44 45
              44:               Label
              46:     19(ptr)   AccessChain 16(inTexCoords) 39
              47:    6(float)   Load 46
              48:    13(bool)   FOrdGreaterThan 47 29
                                Branch 45
              45:             Label
              49:    13(bool) Phi 42 33 48 44
                              SelectionMerge 51 None
                              BranchConditional 49 50 51
              50:               Label
              52:    7(fvec4)   Load 9(resColor)
              53:    7(fvec4)   FMul 52 36
                                Store 9(resColor) 53
                                Branch 51
              51:             Label
              56:    7(fvec4) Load 9(resColor)
                              Store 55(outColor) 56
                              Return
                              FunctionEnd
#endif

static const uint32_t multiple_sets_frag[349] = {
    0x07230203, 0x00010000, 0x00080007, 0x00000039,
    0x00000000, 0x00020011, 0x00000001, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0008000f, 0x00000004, 0x00000004, 0x6e69616d,
    0x00000000, 0x0000000b, 0x00000010, 0x00000037,
    0x00030010, 0x00000004, 0x00000007, 0x00030003,
    0x00000002, 0x00000190, 0x00090004, 0x415f4c47,
    0x735f4252, 0x72617065, 0x5f657461, 0x64616873,
    0x6f5f7265, 0x63656a62, 0x00007374, 0x00090004,
    0x415f4c47, 0x735f4252, 0x69646168, 0x6c5f676e,
    0x75676e61, 0x5f656761, 0x70303234, 0x006b6361,
    0x00040005, 0x00000004, 0x6e69616d, 0x00000000,
    0x00050005, 0x00000009, 0x43736572, 0x726f6c6f,
    0x00000000, 0x00040005, 0x0000000b, 0x6f436e69,
    0x00726f6c, 0x00050005, 0x00000010, 0x65546e69,
    0x6f6f4378, 0x00736472, 0x00050005, 0x00000037,
    0x4374756f, 0x726f6c6f, 0x00000000, 0x00040047,
    0x0000000b, 0x0000001e, 0x00000000, 0x00040047,
    0x00000010, 0x0000001e, 0x00000001, 0x00040047,
    0x00000037, 0x0000001e, 0x00000000, 0x00020013,
    0x00000002, 0x00030021, 0x00000003, 0x00000002,
    0x00030016, 0x00000006, 0x00000020, 0x00040017,
    0x00000007, 0x00000006, 0x00000004, 0x00040020,
    0x00000008, 0x00000007, 0x00000007, 0x00040020,
    0x0000000a, 0x00000001, 0x00000007, 0x0004003b,
    0x0000000a, 0x0000000b, 0x00000001, 0x00020014,
    0x0000000d, 0x00040017, 0x0000000e, 0x00000006,
    0x00000002, 0x00040020, 0x0000000f, 0x00000001,
    0x0000000e, 0x0004003b, 0x0000000f, 0x00000010,
    0x00000001, 0x00040015, 0x00000011, 0x00000020,
    0x00000000, 0x0004002b, 0x00000011, 0x00000012,
    0x00000000, 0x00040020, 0x00000013, 0x00000001,
    0x00000006, 0x0004002b, 0x00000006, 0x00000016,
    0x3c23d70a, 0x0004002b, 0x00000006, 0x0000001d,
    0x3f7d70a4, 0x0004002b, 0x00000006, 0x00000022,
    0x3dcccccd, 0x0004002b, 0x00000006, 0x00000023,
    0x3f800000, 0x0007002c, 0x00000007, 0x00000024,
    0x00000022, 0x00000022, 0x00000022, 0x00000023,
    0x0004002b, 0x00000011, 0x00000027, 0x00000001,
    0x00040020, 0x00000036, 0x00000003, 0x00000007,
    0x0004003b, 0x00000036, 0x00000037, 0x00000003,
    0x00050036, 0x00000002, 0x00000004, 0x00000000,
    0x00000003, 0x000200f8, 0x00000005, 0x0004003b,
    0x00000008, 0x00000009, 0x00000007, 0x0004003d,
    0x00000007, 0x0000000c, 0x0000000b, 0x0003003e,
    0x00000009, 0x0000000c, 0x00050041, 0x00000013,
    0x00000014, 0x00000010, 0x00000012, 0x0004003d,
    0x00000006, 0x00000015, 0x00000014, 0x000500b8,
    0x0000000d, 0x00000017, 0x00000015, 0x00000016,
    0x000400a8, 0x0000000d, 0x00000018, 0x00000017,
    0x000300f7, 0x0000001a, 0x00000000, 0x000400fa,
    0x00000018, 0x00000019, 0x0000001a, 0x000200f8,
    0x00000019, 0x00050041, 0x00000013, 0x0000001b,
    0x00000010, 0x00000012, 0x0004003d, 0x00000006,
    0x0000001c, 0x0000001b, 0x000500ba, 0x0000000d,
    0x0000001e, 0x0000001c, 0x0000001d, 0x000200f9,
    0x0000001a, 0x000200f8, 0x0000001a, 0x000700f5,
    0x0000000d, 0x0000001f, 0x00000017, 0x00000005,
    0x0000001e, 0x00000019, 0x000300f7, 0x00000021,
    0x00000000, 0x000400fa, 0x0000001f, 0x00000020,
    0x00000021, 0x000200f8, 0x00000020, 0x0004003d,
    0x00000007, 0x00000025, 0x00000009, 0x00050085,
    0x00000007, 0x00000026, 0x00000025, 0x00000024,
    0x0003003e, 0x00000009, 0x00000026, 0x000200f9,
    0x00000021, 0x000200f8, 0x00000021, 0x00050041,
    0x00000013, 0x00000028, 0x00000010, 0x00000027,
    0x0004003d, 0x00000006, 0x00000029, 0x00000028,
    0x000500b8, 0x0000000d, 0x0000002a, 0x00000029,
    0x00000016, 0x000400a8, 0x0000000d, 0x0000002b,
    0x0000002a, 0x000300f7, 0x0000002d, 0x00000000,
    0x000400fa, 0x0000002b, 0x0000002c, 0x0000002d,
    0x000200f8, 0x0000002c, 0x00050041, 0x00000013,
    0x0000002e, 0x00000010, 0x00000027, 0x0004003d,
    0x00000006, 0x0000002f, 0x0000002e, 0x000500ba,
    0x0000000d, 0x00000030, 0x0000002f, 0x0000001d,
    0x000200f9, 0x0000002d, 0x000200f8, 0x0000002d,
    0x000700f5, 0x0000000d, 0x00000031, 0x0000002a,
    0x00000021, 0x00000030, 0x0000002c, 0x000300f7,
    0x00000033, 0x00000000, 0x000400fa, 0x00000031,
    0x00000032, 0x00000033, 0x000200f8, 0x00000032,
    0x0004003d, 0x00000007, 0x00000034, 0x00000009,
    0x00050085, 0x00000007, 0x00000035, 0x00000034,
    0x00000024, 0x0003003e, 0x00000009, 0x00000035,
    0x000200f9, 0x00000033, 0x000200f8, 0x00000033,
    0x0004003d, 0x00000007, 0x00000038, 0x00000009,
    0x0003003e, 0x00000037, 0x00000038, 0x000100fd,
    0x00010038,
};
