#include <stdint.h>

#if 0
/usr/local/google/home/gfan/proj/VulkanSamples/API-Samples/android/../pipeline_derivative/pipeline_derivative2.frag
// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 29

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 9 12
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "outColor"
                              Name 12  "texcoord"
                              Decorate 9(outColor) Location 0
                              Decorate 12(texcoord) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Output 7(fvec4)
     9(outColor):      8(ptr) Variable Output
              10:             TypeVector 6(float) 2
              11:             TypePointer Input 10(fvec2)
    12(texcoord):     11(ptr) Variable Input
              13:             TypeInt 32 0
              14:     13(int) Constant 0
              15:             TypePointer Input 6(float)
              18:     13(int) Constant 1
              21:    6(float) Constant 1065353216
         4(main):           2 Function None 3
               5:             Label
              16:     15(ptr) AccessChain 12(texcoord) 14
              17:    6(float) Load 16
              19:     15(ptr) AccessChain 12(texcoord) 18
              20:    6(float) Load 19
              22:     15(ptr) AccessChain 12(texcoord) 14
              23:    6(float) Load 22
              24:    6(float) FSub 21 23
              25:     15(ptr) AccessChain 12(texcoord) 18
              26:    6(float) Load 25
              27:    6(float) FSub 24 26
              28:    7(fvec4) CompositeConstruct 17 20 27 21
                              Store 9(outColor) 28
                              Return
                              FunctionEnd
#endif

static const uint32_t pipeline_derivative2_frag[168] = {
    0x07230203, 0x00010000, 0x00080007, 0x0000001d,
    0x00000000, 0x00020011, 0x00000001, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0007000f, 0x00000004, 0x00000004, 0x6e69616d,
    0x00000000, 0x00000009, 0x0000000c, 0x00030010,
    0x00000004, 0x00000007, 0x00030003, 0x00000002,
    0x000001c2, 0x00040005, 0x00000004, 0x6e69616d,
    0x00000000, 0x00050005, 0x00000009, 0x4374756f,
    0x726f6c6f, 0x00000000, 0x00050005, 0x0000000c,
    0x63786574, 0x64726f6f, 0x00000000, 0x00040047,
    0x00000009, 0x0000001e, 0x00000000, 0x00040047,
    0x0000000c, 0x0000001e, 0x00000000, 0x00020013,
    0x00000002, 0x00030021, 0x00000003, 0x00000002,
    0x00030016, 0x00000006, 0x00000020, 0x00040017,
    0x00000007, 0x00000006, 0x00000004, 0x00040020,
    0x00000008, 0x00000003, 0x00000007, 0x0004003b,
    0x00000008, 0x00000009, 0x00000003, 0x00040017,
    0x0000000a, 0x00000006, 0x00000002, 0x00040020,
    0x0000000b, 0x00000001, 0x0000000a, 0x0004003b,
    0x0000000b, 0x0000000c, 0x00000001, 0x00040015,
    0x0000000d, 0x00000020, 0x00000000, 0x0004002b,
    0x0000000d, 0x0000000e, 0x00000000, 0x00040020,
    0x0000000f, 0x00000001, 0x00000006, 0x0004002b,
    0x0000000d, 0x00000012, 0x00000001, 0x0004002b,
    0x00000006, 0x00000015, 0x3f800000, 0x00050036,
    0x00000002, 0x00000004, 0x00000000, 0x00000003,
    0x000200f8, 0x00000005, 0x00050041, 0x0000000f,
    0x00000010, 0x0000000c, 0x0000000e, 0x0004003d,
    0x00000006, 0x00000011, 0x00000010, 0x00050041,
    0x0000000f, 0x00000013, 0x0000000c, 0x00000012,
    0x0004003d, 0x00000006, 0x00000014, 0x00000013,
    0x00050041, 0x0000000f, 0x00000016, 0x0000000c,
    0x0000000e, 0x0004003d, 0x00000006, 0x00000017,
    0x00000016, 0x00050083, 0x00000006, 0x00000018,
    0x00000015, 0x00000017, 0x00050041, 0x0000000f,
    0x00000019, 0x0000000c, 0x00000012, 0x0004003d,
    0x00000006, 0x0000001a, 0x00000019, 0x00050083,
    0x00000006, 0x0000001b, 0x00000018, 0x0000001a,
    0x00070050, 0x00000007, 0x0000001c, 0x00000011,
    0x00000014, 0x0000001b, 0x00000015, 0x0003003e,
    0x00000009, 0x0000001c, 0x000100fd, 0x00010038,
};
