#include <stdint.h>

#if 0
/usr/local/google/home/gfan/proj/VulkanSamples/API-Samples/android/../push_constants/push_constants.frag
// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 81

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 41 79
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 400
                              SourceExtension  "GL_ARB_separate_shader_objects"
                              SourceExtension  "GL_ARB_shading_language_420pack"
                              Name 4  "main"
                              Name 9  "green"
                              Name 13  "red"
                              Name 15  "resColor"
                              Name 18  "pushBlock"
                              MemberName 18(pushBlock) 0  "iFoo"
                              MemberName 18(pushBlock) 1  "fBar"
                              Name 20  "pushConstantsBlock"
                              Name 41  "inTexCoords"
                              Name 79  "outColor"
                              MemberDecorate 18(pushBlock) 0 Offset 0
                              MemberDecorate 18(pushBlock) 1 Offset 4
                              Decorate 18(pushBlock) Block
                              Decorate 41(inTexCoords) Location 0
                              Decorate 79(outColor) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Function 7(fvec4)
              10:    6(float) Constant 0
              11:    6(float) Constant 1065353216
              12:    7(fvec4) ConstantComposite 10 11 10 11
              14:    7(fvec4) ConstantComposite 11 10 10 11
              17:             TypeInt 32 1
   18(pushBlock):             TypeStruct 17(int) 6(float)
              19:             TypePointer PushConstant 18(pushBlock)
20(pushConstantsBlock):     19(ptr) Variable PushConstant
              21:     17(int) Constant 0
              22:             TypePointer PushConstant 17(int)
              25:     17(int) Constant 2
              26:             TypeBool
              31:     17(int) Constant 1
              32:             TypePointer PushConstant 6(float)
              39:             TypeVector 6(float) 2
              40:             TypePointer Input 39(fvec2)
 41(inTexCoords):     40(ptr) Variable Input
              42:             TypeInt 32 0
              43:     42(int) Constant 0
              44:             TypePointer Input 6(float)
              47:    6(float) Constant 1008981770
              54:    6(float) Constant 1065185444
              59:    6(float) Constant 1036831949
              60:    7(fvec4) ConstantComposite 59 59 59 11
              63:     42(int) Constant 1
              78:             TypePointer Output 7(fvec4)
    79(outColor):     78(ptr) Variable Output
         4(main):           2 Function None 3
               5:             Label
        9(green):      8(ptr) Variable Function
         13(red):      8(ptr) Variable Function
    15(resColor):      8(ptr) Variable Function
                              Store 9(green) 12
                              Store 13(red) 14
              16:    7(fvec4) Load 9(green)
                              Store 15(resColor) 16
              23:     22(ptr) AccessChain 20(pushConstantsBlock) 21
              24:     17(int) Load 23
              27:    26(bool) INotEqual 24 25
                              SelectionMerge 29 None
                              BranchConditional 27 28 29
              28:               Label
              30:    7(fvec4)   Load 13(red)
                                Store 15(resColor) 30
                                Branch 29
              29:             Label
              33:     32(ptr) AccessChain 20(pushConstantsBlock) 31
              34:    6(float) Load 33
              35:    26(bool) FOrdNotEqual 34 11
                              SelectionMerge 37 None
                              BranchConditional 35 36 37
              36:               Label
              38:    7(fvec4)   Load 13(red)
                                Store 15(resColor) 38
                                Branch 37
              37:             Label
              45:     44(ptr) AccessChain 41(inTexCoords) 43
              46:    6(float) Load 45
              48:    26(bool) FOrdLessThan 46 47
              49:    26(bool) LogicalNot 48
                              SelectionMerge 51 None
                              BranchConditional 49 50 51
              50:               Label
              52:     44(ptr)   AccessChain 41(inTexCoords) 43
              53:    6(float)   Load 52
              55:    26(bool)   FOrdGreaterThan 53 54
                                Branch 51
              51:             Label
              56:    26(bool) Phi 48 37 55 50
                              SelectionMerge 58 None
                              BranchConditional 56 57 58
              57:               Label
              61:    7(fvec4)   Load 15(resColor)
              62:    7(fvec4)   FMul 61 60
                                Store 15(resColor) 62
                                Branch 58
              58:             Label
              64:     44(ptr) AccessChain 41(inTexCoords) 63
              65:    6(float) Load 64
              66:    26(bool) FOrdLessThan 65 47
              67:    26(bool) LogicalNot 66
                              SelectionMerge 69 None
                              BranchConditional 67 68 69
              68:               Label
              70:     44(ptr)   AccessChain 41(inTexCoords) 63
              71:    6(float)   Load 70
              72:    26(bool)   FOrdGreaterThan 71 54
                                Branch 69
              69:             Label
              73:    26(bool) Phi 66 58 72 68
                              SelectionMerge 75 None
                              BranchConditional 73 74 75
              74:               Label
              76:    7(fvec4)   Load 15(resColor)
              77:    7(fvec4)   FMul 76 60
                                Store 15(resColor) 77
                                Branch 75
              75:             Label
              80:    7(fvec4) Load 15(resColor)
                              Store 79(outColor) 80
                              Return
                              FunctionEnd
#endif

static const uint32_t push_constants_frag[510] = {
    0x07230203, 0x00010000, 0x00080007, 0x00000051,
    0x00000000, 0x00020011, 0x00000001, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0007000f, 0x00000004, 0x00000004, 0x6e69616d,
    0x00000000, 0x00000029, 0x0000004f, 0x00030010,
    0x00000004, 0x00000007, 0x00030003, 0x00000002,
    0x00000190, 0x00090004, 0x415f4c47, 0x735f4252,
    0x72617065, 0x5f657461, 0x64616873, 0x6f5f7265,
    0x63656a62, 0x00007374, 0x00090004, 0x415f4c47,
    0x735f4252, 0x69646168, 0x6c5f676e, 0x75676e61,
    0x5f656761, 0x70303234, 0x006b6361, 0x00040005,
    0x00000004, 0x6e69616d, 0x00000000, 0x00040005,
    0x00000009, 0x65657267, 0x0000006e, 0x00030005,
    0x0000000d, 0x00646572, 0x00050005, 0x0000000f,
    0x43736572, 0x726f6c6f, 0x00000000, 0x00050005,
    0x00000012, 0x68737570, 0x636f6c42, 0x0000006b,
    0x00050006, 0x00000012, 0x00000000, 0x6f6f4669,
    0x00000000, 0x00050006, 0x00000012, 0x00000001,
    0x72614266, 0x00000000, 0x00070005, 0x00000014,
    0x68737570, 0x736e6f43, 0x746e6174, 0x6f6c4273,
    0x00006b63, 0x00050005, 0x00000029, 0x65546e69,
    0x6f6f4378, 0x00736472, 0x00050005, 0x0000004f,
    0x4374756f, 0x726f6c6f, 0x00000000, 0x00050048,
    0x00000012, 0x00000000, 0x00000023, 0x00000000,
    0x00050048, 0x00000012, 0x00000001, 0x00000023,
    0x00000004, 0x00030047, 0x00000012, 0x00000002,
    0x00040047, 0x00000029, 0x0000001e, 0x00000000,
    0x00040047, 0x0000004f, 0x0000001e, 0x00000000,
    0x00020013, 0x00000002, 0x00030021, 0x00000003,
    0x00000002, 0x00030016, 0x00000006, 0x00000020,
    0x00040017, 0x00000007, 0x00000006, 0x00000004,
    0x00040020, 0x00000008, 0x00000007, 0x00000007,
    0x0004002b, 0x00000006, 0x0000000a, 0x00000000,
    0x0004002b, 0x00000006, 0x0000000b, 0x3f800000,
    0x0007002c, 0x00000007, 0x0000000c, 0x0000000a,
    0x0000000b, 0x0000000a, 0x0000000b, 0x0007002c,
    0x00000007, 0x0000000e, 0x0000000b, 0x0000000a,
    0x0000000a, 0x0000000b, 0x00040015, 0x00000011,
    0x00000020, 0x00000001, 0x0004001e, 0x00000012,
    0x00000011, 0x00000006, 0x00040020, 0x00000013,
    0x00000009, 0x00000012, 0x0004003b, 0x00000013,
    0x00000014, 0x00000009, 0x0004002b, 0x00000011,
    0x00000015, 0x00000000, 0x00040020, 0x00000016,
    0x00000009, 0x00000011, 0x0004002b, 0x00000011,
    0x00000019, 0x00000002, 0x00020014, 0x0000001a,
    0x0004002b, 0x00000011, 0x0000001f, 0x00000001,
    0x00040020, 0x00000020, 0x00000009, 0x00000006,
    0x00040017, 0x00000027, 0x00000006, 0x00000002,
    0x00040020, 0x00000028, 0x00000001, 0x00000027,
    0x0004003b, 0x00000028, 0x00000029, 0x00000001,
    0x00040015, 0x0000002a, 0x00000020, 0x00000000,
    0x0004002b, 0x0000002a, 0x0000002b, 0x00000000,
    0x00040020, 0x0000002c, 0x00000001, 0x00000006,
    0x0004002b, 0x00000006, 0x0000002f, 0x3c23d70a,
    0x0004002b, 0x00000006, 0x00000036, 0x3f7d70a4,
    0x0004002b, 0x00000006, 0x0000003b, 0x3dcccccd,
    0x0007002c, 0x00000007, 0x0000003c, 0x0000003b,
    0x0000003b, 0x0000003b, 0x0000000b, 0x0004002b,
    0x0000002a, 0x0000003f, 0x00000001, 0x00040020,
    0x0000004e, 0x00000003, 0x00000007, 0x0004003b,
    0x0000004e, 0x0000004f, 0x00000003, 0x00050036,
    0x00000002, 0x00000004, 0x00000000, 0x00000003,
    0x000200f8, 0x00000005, 0x0004003b, 0x00000008,
    0x00000009, 0x00000007, 0x0004003b, 0x00000008,
    0x0000000d, 0x00000007, 0x0004003b, 0x00000008,
    0x0000000f, 0x00000007, 0x0003003e, 0x00000009,
    0x0000000c, 0x0003003e, 0x0000000d, 0x0000000e,
    0x0004003d, 0x00000007, 0x00000010, 0x00000009,
    0x0003003e, 0x0000000f, 0x00000010, 0x00050041,
    0x00000016, 0x00000017, 0x00000014, 0x00000015,
    0x0004003d, 0x00000011, 0x00000018, 0x00000017,
    0x000500ab, 0x0000001a, 0x0000001b, 0x00000018,
    0x00000019, 0x000300f7, 0x0000001d, 0x00000000,
    0x000400fa, 0x0000001b, 0x0000001c, 0x0000001d,
    0x000200f8, 0x0000001c, 0x0004003d, 0x00000007,
    0x0000001e, 0x0000000d, 0x0003003e, 0x0000000f,
    0x0000001e, 0x000200f9, 0x0000001d, 0x000200f8,
    0x0000001d, 0x00050041, 0x00000020, 0x00000021,
    0x00000014, 0x0000001f, 0x0004003d, 0x00000006,
    0x00000022, 0x00000021, 0x000500b6, 0x0000001a,
    0x00000023, 0x00000022, 0x0000000b, 0x000300f7,
    0x00000025, 0x00000000, 0x000400fa, 0x00000023,
    0x00000024, 0x00000025, 0x000200f8, 0x00000024,
    0x0004003d, 0x00000007, 0x00000026, 0x0000000d,
    0x0003003e, 0x0000000f, 0x00000026, 0x000200f9,
    0x00000025, 0x000200f8, 0x00000025, 0x00050041,
    0x0000002c, 0x0000002d, 0x00000029, 0x0000002b,
    0x0004003d, 0x00000006, 0x0000002e, 0x0000002d,
    0x000500b8, 0x0000001a, 0x00000030, 0x0000002e,
    0x0000002f, 0x000400a8, 0x0000001a, 0x00000031,
    0x00000030, 0x000300f7, 0x00000033, 0x00000000,
    0x000400fa, 0x00000031, 0x00000032, 0x00000033,
    0x000200f8, 0x00000032, 0x00050041, 0x0000002c,
    0x00000034, 0x00000029, 0x0000002b, 0x0004003d,
    0x00000006, 0x00000035, 0x00000034, 0x000500ba,
    0x0000001a, 0x00000037, 0x00000035, 0x00000036,
    0x000200f9, 0x00000033, 0x000200f8, 0x00000033,
    0x000700f5, 0x0000001a, 0x00000038, 0x00000030,
    0x00000025, 0x00000037, 0x00000032, 0x000300f7,
    0x0000003a, 0x00000000, 0x000400fa, 0x00000038,
    0x00000039, 0x0000003a, 0x000200f8, 0x00000039,
    0x0004003d, 0x00000007, 0x0000003d, 0x0000000f,
    0x00050085, 0x00000007, 0x0000003e, 0x0000003d,
    0x0000003c, 0x0003003e, 0x0000000f, 0x0000003e,
    0x000200f9, 0x0000003a, 0x000200f8, 0x0000003a,
    0x00050041, 0x0000002c, 0x00000040, 0x00000029,
    0x0000003f, 0x0004003d, 0x00000006, 0x00000041,
    0x00000040, 0x000500b8, 0x0000001a, 0x00000042,
    0x00000041, 0x0000002f, 0x000400a8, 0x0000001a,
    0x00000043, 0x00000042, 0x000300f7, 0x00000045,
    0x00000000, 0x000400fa, 0x00000043, 0x00000044,
    0x00000045, 0x000200f8, 0x00000044, 0x00050041,
    0x0000002c, 0x00000046, 0x00000029, 0x0000003f,
    0x0004003d, 0x00000006, 0x00000047, 0x00000046,
    0x000500ba, 0x0000001a, 0x00000048, 0x00000047,
    0x00000036, 0x000200f9, 0x00000045, 0x000200f8,
    0x00000045, 0x000700f5, 0x0000001a, 0x00000049,
    0x00000042, 0x0000003a, 0x00000048, 0x00000044,
    0x000300f7, 0x0000004b, 0x00000000, 0x000400fa,
    0x00000049, 0x0000004a, 0x0000004b, 0x000200f8,
    0x0000004a, 0x0004003d, 0x00000007, 0x0000004c,
    0x0000000f, 0x00050085, 0x00000007, 0x0000004d,
    0x0000004c, 0x0000003c, 0x0003003e, 0x0000000f,
    0x0000004d, 0x000200f9, 0x0000004b, 0x000200f8,
    0x0000004b, 0x0004003d, 0x00000007, 0x00000050,
    0x0000000f, 0x0003003e, 0x0000004f, 0x00000050,
    0x000100fd, 0x00010038,
};
